# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Untaint-creditcard
version:      1.00
version_from: lib/CGI/Untaint/creditcard.pm
installdirs:  site
requires:
    Business::CreditCard::Object:  0
    CGI::Untaint:                  0.01
    Test::More:                    0.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
